disabled_rules:
  - line_length

identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - db

unused_closure_parameter: disabled

function_body_length:
  ignores_comments: true
  warning: 100
